### ISSUE TITLE
Build error

### ISSUE THREAD

**Issue by magaton** [graphaware/recommendations-meetup#1]
[ERROR] Failed to execute goal on project recommendation-engine: Could not resolve dependencies for project com.graphaware.meetup:recommendation-engine:jar:1.0-SNAPSHOT: Failure to find org.neo4j:neo4j-spatial:jar:0.15-neo4j-2.3.0 in http://repo.maven.apache.org/maven2 was cached in the local repository, resolution will not be reattempted until the update interval of central has elapsed or updates are forced -> [Help 1]

**Comment by magaton** [comment]
This repository seems
<repository>
            <id>neo4j-contrib-releases</id>
            <url>https://raw.github.com/neo4j-contrib/m2/master/releases</url>
            <releases>
                <enabled>true</enabled>
            </releases>
            <snapshots>
                <enabled>false</enabled>
            </snapshots>
        </repository>

**Comment by magaton** [comment]
https://github.com/graphaware/recommendations-meetup/pull/2

**Comment by bachmanm** [comment]
thanks for the PR
